version: '3.8'

services:
  mongodb:
    image: mongo:8.0
    restart: always
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
  mongodb_data:
  backend_node_modules:
  frontend_node_modules:
  terminal_settings: 